### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by petk** [phpcommunity/phptestfest-php-src#154]
Hello, is there any plan to merge the approved tests to the upstream php-src repository? If not, can we start adding these on our own via separate pull requests there?

**Comment by coudenysj** [comment]
https://groups.google.com/a/phpcommunity.org/forum/#!msg/testfest/wUqnvcufIjE/77keUjzBBgAJ

**Comment by petk** [comment]
This is now in progress... See https://externals.io/message/104224
