### ISSUE TITLE
When the PRs will be on php-src?

### ISSUE THREAD

**Issue by royopa** [phpcommunity/phptestfest-php-src#156]
Hi guys!

When the PRs will be on php-src?

Regards

royopa

**Comment by petk** [comment]
Hello, I've found out that discussion is happening here:
https://groups.google.com/a/phpcommunity.org/forum/#!msg/testfest/wUqnvcufIjE/77keUjzBBgAJ

**Comment by carusogabriel** [comment]
Hello everyone.

I'll be taking a look into this PRs in this weekend, commenting those ones that aren't necessary or were created meanwhile, so we can get they all merged into https://github.com/php/php-src.

**Comment by royopa** [comment]
Thanks Gabriel!

**Comment by coudenysj** [comment]
Thank you @krakjoe, @carusogabriel & @petk for the time to plough through the pull requests and merging the good ones upstream!

**Comment by petk** [comment]
Hello, I want to thank everyone who have sent their pull requests here or have in any other way joined and participated in the PHP test fest event.

I thought we could merge all the pull requests properly in few months but unfortunately that's it from my side in the given time frame that was set for this part. We have merged several pull requests that could be added in the upstream repository others should be done manually but I simply don't have time to go through each manually anymore. If you'd like to see your contribution noted in the php-src, please reopen your pull request in the php-src repository directly. It's very simple (and in most cases hopefully welcoming enough) to send your pull request there. If not ping me up to check your pull requests per manual basis.

A friendly nudge to the organizers... Next time, don't be shy and please please avoid doing forks of this repo and let's do the noise directly on the php-src repo. As we see, it is almost near impossible to solve this properly and give everyone credits they deserve and merge all the pull requests there without manual commits and rechecks without the help of the internals people.

@michele-damiano, @ymln, @hannesvdvreken, @mcq8, @royopa, @nielsvermaut, @p365labs, @wakuseo, @LucaGallinari, @alexmanno, @mmenozzi, @drapisarda, @drapisarda, @stefano-rainieri, @stefano-rainieri, @massimilianobraglia, @starvagrant, @gabrieldagama, @globtec, @kenguest, @kenguest, @ericpoe, @dwhobbs, @raniery, @vitormattos, @yuklia, @liam-wiltshire, @dstockto, @BlackIkeEagle thank you so much for your contribution 🥇 and wish you as least buggy upcoming PHP 7.4 release 🎉 

Cheers and thanks.
