### ISSUE TITLE
Question about Closed bugs and their tests

### ISSUE THREAD

**Issue by yuklia** [phpcommunity/phptestfest-php-src#75]
What should I do if I see bug is [Closed](https://bugs.php.net/bug.php?id=62904) but there is still test file in repo `phptestfest-php-src/ext/spl/tests/bug62904.phpt` ?

I suggest removing the `bug62904.phpt` and write basic tests instead.

**Comment by krakjoe** [comment]
The test in question, and many similarly named tests, are regression tests. We name them like that so that upon regression, we have a record of the report and the original fix (we know exactly what we broke).

This is very normal, and doesn't need moving/renaming/anything.
